#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#  Sync IPTSP Manager Config with Asterisk Server
#  Pulls SIP numbers from database and updates Asterisk configs
# ═══════════════════════════════════════════════════════════════════

set -e

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'

ok()     { echo -e "${GREEN}[✓]${NC} $1"; }
warn()   { echo -e "${YELLOW}[!]${NC} $1"; }
fail()   { echo -e "${RED}[✗]${NC} $1"; }
info()   { echo -e "${BLUE}[i]${NC} $1"; }

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root${NC}"
    exit 1
fi

# Configuration
ASTERSK_CONFIG_DIR="/etc/asterisk"
BACKUP_DIR="/etc/asterisk/backup"
IPTSP_DATA_FILE="/root/iptsp_data.json"

echo ""
echo "============================================"
echo "  IPTSP Config Sync"
echo "  Asterisk Configuration Generator"
echo "============================================"
echo ""

# Backup current configs
info "Backing up current configurations..."
mkdir -p "$BACKUP_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
cp "$ASTERSK_CONFIG_DIR/pjsip.conf" "$BACKUP_DIR/pjsip.conf.$TIMESTAMP" 2>/dev/null || true
cp "$ASTERSK_CONFIG_DIR/extensions.conf" "$BACKUP_DIR/extensions.conf.$TIMESTAMP" 2>/dev/null || true
cp "$ASTERSK_CONFIG_DIR/sip.conf" "$BACKUP_DIR/sip.conf.$TIMESTAMP" 2>/dev/null || true
ok "Backup created: $BACKUP_DIR/*.conf.$TIMESTAMP"

# Read IPTSP data (from localStorage export or API)
if [ -f "$IPTSP_DATA_FILE" ]; then
    info "Reading IPTSP data from $IPTSP_DATA_FILE"
    # Parse JSON data (requires jq)
    if ! command -v jq &> /dev/null; then
        warn "jq not installed - installing..."
        apt-get install -y jq 2>/dev/null || yum install -y jq 2>/dev/null || true
    fi
else
    info "No IPTSP data file found - generating template configs"
fi

# Generate PJSIP config
info "Generating pjsip.conf..."

cat > "$ASTERSK_CONFIG_DIR/pjsip.conf" <<'CONF'
; ═══════════════════════════════════════════════════════════════════
;  IPTSP PJSIP Configuration
;  Auto-generated by sync_asterisk_config.sh
;  Generated: TIMESTAMP_PLACEHOLDER
; ═══════════════════════════════════════════════════════════════════

[global]
type=global
endpoint_identifier_order=ip,username,anonymous
max_forwards=70
user_agent=IPTSP-Asterisk

; ───────────────────────────────────────────────────────────────────
;  Transports
; ───────────────────────────────────────────────────────────────────

[transport-udp-bangladesh]
type=transport
protocol=udp
bind=0.0.0.0:5080
external_media_address=auto
external_signaling_address=auto

[transport-udp-india]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=auto
external_signaling_address=auto

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

; ───────────────────────────────────────────────────────────────────
;  Endpoint Templates
; ───────────────────────────────────────────────────────────────────

[endpoint-bangladesh](!)
type=endpoint
context=bangladesh-inbound
disallow=all
allow=ulaw
allow=alaw
allow=gsm
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
qualify_frequency=60
dtmf_mode=rfc2833
ice_support=no
identify_by=user

[endpoint-india](!)
type=endpoint
context=india-outbound
disallow=all
allow=g729
allow=ulaw
allow=alaw
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
qualify_frequency=60
dtmf_mode=rfc2833

[auth-basic](!)
type=auth
auth_type=userpass

[aor-dynamic](!)
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
qualify_timeout=3

; ───────────────────────────────────────────────────────────────────
;  Bangladesh SIP Numbers
;  Format: [auth-number], [aor-number], [endpoint-number]
;  Add your numbers below or use IPTSP Manager GUI
; ───────────────────────────────────────────────────────────────────

; Example Bangladesh Number
; [auth-bd-8801712345678](auth-basic)
; username=+8801712345678
; password=YourPasswordHere
; 
; [aor-bd-8801712345678](aor-dynamic)
; mailboxes=8801712345678@bangladesh
; 
; [endpoint-bd-8801712345678](endpoint-bangladesh)
; auth=auth-bd-8801712345678
; aors=aor-bd-8801712345678
; callerid="+8801712345678" <+8801712345678>
; from_domain=10.100.0.1

; ───────────────────────────────────────────────────────────────────
;  India SIP Trunk
; ───────────────────────────────────────────────────────────────────

[india-trunk-auth](auth-basic)
username=+914223532220
password=TrunkPassword123

[india-trunk-aor](aor-dynamic)
contact=sip:100.64.216.4:5060
qualify_frequency=30

[india-trunk-endpoint](endpoint-india)
auth=india-trunk-auth
aors=india-trunk-aor
from_domain=100.65.166.6
outbound_auth=india-trunk-auth

[india-trunk-identify]
type=identify
endpoint=india-trunk-endpoint
match=100.64.216.4

; ───────────────────────────────────────────────────────────────────
;  Registration
; ───────────────────────────────────────────────────────────────────

[register-india]
type=registration
transport=transport-udp-india
outbound_auth=india-trunk-auth
server_uri=sip:100.65.166.6:5060
client_uri=sip:+914223532220@100.65.166.6:5060
contact_header=sip:+914223532220@10.200.0.1:5060
retry_interval=60
forbidden_interval=3600
expiration=3600

CONF

# Replace timestamp
sed -i "s/TIMESTAMP_PLACEHOLDER/$(date)/" "$ASTERSK_CONFIG_DIR/pjsip.conf"
ok "pjsip.conf generated"

# Generate extensions.conf
info "Generating extensions.conf..."

cat > "$ASTERSK_CONFIG_DIR/extensions.conf" <<'CONF'
; ═══════════════════════════════════════════════════════════════════
;  IPTSP Extensions Configuration
;  Auto-generated by sync_asterisk_config.sh
; ═══════════════════════════════════════════════════════════════════

[general]
static=yes
writeprotect=no
autofallthrough=yes
clearglobalvars=no

[globals]
BANGLADESH_CONTEXT=bangladesh-inbound
INDIA_CONTEXT=india-outbound
SBC_IP=100.64.216.4
SBC_DOMAIN=100.65.166.6

; ───────────────────────────────────────────────────────────────────
;  Bangladesh Inbound Context
; ───────────────────────────────────────────────────────────────────

[bangladesh-inbound]
; India International: 0091XXXXXXXXXX
exten => _0091X.,1,NoOp(India International Call)
 same => n,Set(CALLERID(num)=\${CALLERID(num)})
 same => n,Dial(PJSIP/\${EXTEN:4}@india-trunk-endpoint,60)
 same => n,Hangup()

; India International with +: +91XXXXXXXXXX
exten => _+91X.,1,NoOp(India International Call with +)
 same => n,Dial(PJSIP/\${EXTEN:1}@india-trunk-endpoint,60)
 same => n,Hangup()

; Bangladesh Local: 01XXXXXXXXX
exten => _01X.,1,NoOp(Bangladesh Local Call)
 same => n,Dial(PJSIP/\${EXTEN},30)
 same => n,Hangup()

; Bangladesh with +880: +8801XXXXXXXXX
exten => _+8801X.,1,NoOp(Bangladesh Local with +880)
 same => n,Dial(PJSIP/\${EXTEN:4},30)
 same => n,Hangup()

; Echo Test
exten => 9999,1,NoOp(Echo Test)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()

; ───────────────────────────────────────────────────────────────────
;  India Outbound Context
; ───────────────────────────────────────────────────────────────────

[india-outbound]
; Bangladesh International from India: 008801XXXXXXXXX
exten => _008801X.,1,NoOp(Bangladesh International from India)
 same => n,Set(CALLERID(num)=\${CALLERID(num)})
 same => n,Dial(PJSIP/\${EXTEN:5}@bangladesh-inbound,60)
 same => n,Hangup()

; Bangladesh from India with +: +8801XXXXXXXXX
exten => _+8801X.,1,NoOp(Bangladesh from India with +)
 same => n,Dial(PJSIP/\${EXTEN:4}@bangladesh-inbound,60)
 same => n,Hangup()

; India Local: 0XXXXXXXXX
exten => _0X.,1,NoOp(India Local Call)
 same => n,Dial(PJSIP/\${EXTEN}@india-trunk-endpoint,60)
 same => n,Hangup()

; ───────────────────────────────────────────────────────────────────
;  Default Context
; ───────────────────────────────────────────────────────────────────

[default]
include => bangladesh-inbound
include => india-outbound

exten => h,1,NoOp(Hangup handler)
 same => n,Hangup()

CONF

ok "extensions.conf generated"

# Generate legacy sip.conf
info "Generating sip.conf (legacy)..."

cat > "$ASTERSK_CONFIG_DIR/sip.conf" <<'CONF'
; ═══════════════════════════════════════════════════════════════════
;  IPTSP Legacy SIP Configuration
;  For devices that don't support PJSIP
; ═══════════════════════════════════════════════════════════════════

[general]
context=default
bindport=5080
bindaddr=0.0.0.0
language=en
disallow=all
allow=ulaw
allow=alaw
allow=gsm
nat=force_rport,comedia
qualify=yes
alwaysauthreject=yes
canreinvite=no
session-timers=refuse
defaultexpiry=120
minexpiry=60
maxexpiry=3600

; ───────────────────────────────────────────────────────────────────
;  Bangladesh Numbers (Legacy)
;  Add your numbers here
; ───────────────────────────────────────────────────────────────────

; Example:
; [8801712345678]
; type=friend
; context=bangladesh-inbound
; host=dynamic
; secret=YourPasswordHere
; callerid="+8801712345678" <8801712345678>
; disallow=all
; allow=ulaw
; allow=alaw
; nat=yes
; dtmfmode=rfc2833

; ───────────────────────────────────────────────────────────────────
;  India Trunk (Legacy Peer)
; ───────────────────────────────────────────────────────────────────

[india-trunk]
type=peer
host=100.64.216.4
port=5060
nat=yes
insecure=invite,port
fromdomain=100.65.166.6
dtmfmode=rfc2833
disallow=all
allow=g729
allow=ulaw
allow=alaw
context=india-outbound
defaultuser=+914223532220
canreinvite=no

CONF

ok "sip.conf generated"

# Set permissions
chown -R asterisk:asterisk "$ASTERSK_CONFIG_DIR"
chmod 640 "$ASTERSK_CONFIG_DIR"/*.conf
ok "Permissions set"

# Reload Asterisk
info "Reloading Asterisk configuration..."
if systemctl is-active --quiet asterisk; then
    asterisk -rx "core reload" 2>/dev/null && ok "Asterisk reloaded" || warn "Reload failed"
    asterisk -rx "pjsip reload" 2>/dev/null && ok "PJSIP reloaded" || warn "PJSIP reload failed"
else
    warn "Asterisk is not running"
fi

# Show summary
echo ""
echo "════════════════════════════════════════"
echo "  SYNC COMPLETE"
echo "════════════════════════════════════════"
echo ""
echo "Configuration files updated:"
echo "  • $ASTERSK_CONFIG_DIR/pjsip.conf"
echo "  • $ASTERSK_CONFIG_DIR/extensions.conf"
echo "  • $ASTERSK_CONFIG_DIR/sip.conf"
echo ""
echo "Backup location: $BACKUP_DIR"
echo ""
echo "To add SIP numbers:"
echo "  1. Edit pjsip.conf and add [auth-*], [aor-*], [endpoint-*] sections"
echo "  2. Run: asterisk -rx 'pjsip reload'"
echo "  3. Or use IPTSP Manager GUI to manage numbers"
echo ""
echo "Verify:"
echo "  • asterisk -rx 'pjsip show endpoints'"
echo "  • asterisk -rx 'sip show peers'"
echo "  • asterisk -rx 'core show channels'"
echo ""
