import { useState } from 'react';
import { useData } from '../contexts/DataContext';
import { WireGuardConfig } from '../types';
import { 
  Plus, 
  Edit2, 
  Trash2, 
  Shield,
  X,
  Copy,
  Check,
  Download,
  Activity
} from 'lucide-react';

export default function WireGuard() {
  const { wireGuardConfigs, addWireGuardConfig, updateWireGuardConfig, deleteWireGuardConfig } = useData();
  const [showModal, setShowModal] = useState(false);
  const [editingConfig, setEditingConfig] = useState<WireGuardConfig | null>(null);
  const [showConfig, setShowConfig] = useState<WireGuardConfig | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    name: '',
    country: 'bangladesh' as 'bangladesh' | 'india',
    interfaceIp: '',
    endpoint: '',
    port: 51820,
    allowedIps: ['10.100.0.0/24'],
    status: 'configuring' as 'connected' | 'disconnected' | 'configuring',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Generate keys
    const privateKey = Array.from({ length: 44 }, () => 
      'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='[Math.floor(Math.random() * 65)]
    ).join('');
    const publicKey = Array.from({ length: 44 }, () => 
      'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='[Math.floor(Math.random() * 65)]
    ).join('');
    
    if (editingConfig) {
      updateWireGuardConfig(editingConfig.id, {
        ...formData,
        privateKey: editingConfig.privateKey,
        publicKey: editingConfig.publicKey,
      });
    } else {
      addWireGuardConfig({
        ...formData,
        privateKey,
        publicKey,
      });
    }
    
    closeModal();
  };

  const openModal = (config?: WireGuardConfig) => {
    if (config) {
      setEditingConfig(config);
      setFormData({
        name: config.name,
        country: config.country,
        interfaceIp: config.interfaceIp,
        endpoint: config.endpoint,
        port: config.port,
        allowedIps: config.allowedIps,
        status: config.status,
      });
    } else {
      setEditingConfig(null);
      setFormData({
        name: '',
        country: 'bangladesh',
        interfaceIp: '',
        endpoint: '',
        port: 51820,
        allowedIps: ['10.100.0.0/24'],
        status: 'configuring',
      });
    }
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setEditingConfig(null);
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const generateWireGuardConfig = (config: WireGuardConfig) => {
    return `# WireGuard Configuration for ${config.name}
# Generated by IPTSP Manager

[Interface]
PrivateKey = ${config.privateKey}
Address = ${config.interfaceIp}/24
ListenPort = ${config.port}
# PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Bangladesh/India Relay Server
PublicKey = ${config.publicKey}
Endpoint = ${config.endpoint}
AllowedIPs = ${config.allowedIps.join(', ')}
PersistentKeepalive = 25

# Client Configuration (for SIP devices)
# [Interface]
# PrivateKey = <client-private-key>
# Address = 10.${config.country === 'bangladesh' ? '100' : '200'}.0.x/24
# DNS = 8.8.8.8
#
# [Peer]
# PublicKey = ${config.publicKey}
# Endpoint = ${config.endpoint}
# AllowedIPs = 0.0.0.0/0
# PersistentKeepalive = 25
`;
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'connected': return 'bg-green-500/20 text-green-400 border-green-500/30';
      case 'disconnected': return 'bg-red-500/20 text-red-400 border-red-500/30';
      case 'configuring': return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30';
      default: return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">WireGuard VPN</h1>
          <p className="text-blue-200">Manage WireGuard tunnels for Bangladesh & India SIP relay</p>
        </div>
        <button
          onClick={() => openModal()}
          className="flex items-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-xl transition-all shadow-lg shadow-purple-500/30"
        >
          <Plus className="w-5 h-5" />
          Add Tunnel
        </button>
      </div>

      {/* Info Banner */}
      <div className="bg-purple-600/20 border border-purple-500/30 rounded-2xl p-6">
        <div className="flex items-start gap-4">
          <Shield className="w-8 h-8 text-purple-400 flex-shrink-0" />
          <div>
            <h3 className="text-lg font-semibold text-white mb-2">WireGuard for SIP Trunking</h3>
            <p className="text-purple-200 text-sm">
              WireGuard tunnels provide secure connectivity for SIP traffic between Bangladesh and India. 
              All SIP numbers register through the WireGuard relay to bypass port restrictions. 
              Port 5060 is blocked in Bangladesh - use alternative ports (5080, 5081, 5082) for UDP traffic.
            </p>
          </div>
        </div>
      </div>

      {/* Tunnels Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {wireGuardConfigs.map((config) => (
          <div key={config.id} className="bg-white/10 backdrop-blur-lg rounded-2xl border border-white/20 p-6 hover:bg-white/15 transition-all">
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className={`p-3 rounded-xl ${config.country === 'bangladesh' ? 'bg-green-600' : 'bg-orange-600'}`}>
                  <Shield className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-white">{config.name}</h3>
                  <p className="text-sm text-blue-200">{config.country === 'bangladesh' ? '🇧🇩 Bangladesh' : '🇮🇳 India'} Relay</p>
                </div>
              </div>
              <span className={`px-3 py-1 rounded-full text-xs font-medium border flex items-center gap-2 ${getStatusColor(config.status)}`}>
                <span className={`w-2 h-2 rounded-full ${config.status === 'connected' ? 'bg-green-400 animate-pulse' : config.status === 'disconnected' ? 'bg-red-400' : 'bg-yellow-400'}`} />
                {config.status}
              </span>
            </div>

            <div className="space-y-3 mb-4">
              <div className="flex justify-between items-center p-3 bg-white/5 rounded-lg">
                <span className="text-blue-200 text-sm">Interface IP</span>
                <div className="flex items-center gap-2">
                  <span className="text-white font-mono text-sm">{config.interfaceIp}</span>
                  <button
                    onClick={() => copyToClipboard(config.interfaceIp, `ip-${config.id}`)}
                    className="p-1 hover:bg-white/10 rounded transition-colors"
                  >
                    {copiedId === `ip-${config.id}` ? (
                      <Check className="w-4 h-4 text-green-400" />
                    ) : (
                      <Copy className="w-4 h-4 text-blue-300" />
                    )}
                  </button>
                </div>
              </div>
              <div className="flex justify-between items-center p-3 bg-white/5 rounded-lg">
                <span className="text-blue-200 text-sm">Endpoint</span>
                <span className="text-white font-mono text-sm">{config.endpoint}</span>
              </div>
              <div className="flex justify-between items-center p-3 bg-white/5 rounded-lg">
                <span className="text-blue-200 text-sm">Port</span>
                <span className="text-white font-mono text-sm">{config.port}</span>
              </div>
              <div className="flex justify-between items-center p-3 bg-white/5 rounded-lg">
                <span className="text-blue-200 text-sm">Allowed IPs</span>
                <span className="text-white font-mono text-sm">{config.allowedIps.join(', ')}</span>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3 pt-4 border-t border-white/10">
              <button
                onClick={() => setShowConfig(config)}
                className="flex items-center justify-center gap-2 px-4 py-2 bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/30 rounded-lg text-purple-300 hover:text-purple-200 transition-all"
              >
                <Activity className="w-4 h-4" />
                View Config
              </button>
              <button
                onClick={() => {
                  const configText = generateWireGuardConfig(config);
                  const blob = new Blob([configText], { type: 'text/plain' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = `wireguard-${config.country}-${config.name.toLowerCase().replace(/\s+/g, '-')}.conf`;
                  a.click();
                  URL.revokeObjectURL(url);
                }}
                className="flex items-center justify-center gap-2 px-4 py-2 bg-blue-600/20 hover:bg-blue-600/30 border border-blue-500/30 rounded-lg text-blue-300 hover:text-blue-200 transition-all"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
              <button
                onClick={() => openModal(config)}
                className="flex items-center justify-center gap-2 px-4 py-2 bg-emerald-600/20 hover:bg-emerald-600/30 border border-emerald-500/30 rounded-lg text-emerald-300 hover:text-emerald-200 transition-all"
              >
                <Edit2 className="w-4 h-4" />
                Edit
              </button>
              <button
                onClick={() => {
                  if (confirm('Are you sure you want to delete this tunnel?')) {
                    deleteWireGuardConfig(config.id);
                  }
                }}
                className="flex items-center justify-center gap-2 px-4 py-2 bg-red-600/20 hover:bg-red-600/30 border border-red-500/30 rounded-lg text-red-300 hover:text-red-200 transition-all"
              >
                <Trash2 className="w-4 h-4" />
                Delete
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Config Modal */}
      {showConfig && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-slate-900 rounded-2xl border border-white/20 w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between p-6 border-b border-white/10">
              <h2 className="text-xl font-semibold text-white">WireGuard Configuration</h2>
              <button onClick={() => setShowConfig(null)} className="p-2 hover:bg-white/10 rounded-lg transition-colors">
                <X className="w-5 h-5 text-blue-300" />
              </button>
            </div>
            <div className="p-6 overflow-auto flex-1">
              <pre className="bg-black/50 rounded-xl p-4 text-sm font-mono text-green-400 overflow-x-auto">
                {generateWireGuardConfig(showConfig)}
              </pre>
            </div>
            <div className="p-6 border-t border-white/10 flex gap-3">
              <button
                onClick={() => {
                  copyToClipboard(generateWireGuardConfig(showConfig), 'config');
                }}
                className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-xl transition-all"
              >
                {copiedId === 'config' ? (
                  <>
                    <Check className="w-5 h-5" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-5 h-5" />
                    Copy Config
                  </>
                )}
              </button>
              <button
                onClick={() => setShowConfig(null)}
                className="flex-1 px-6 py-3 bg-white/10 hover:bg-white/20 text-white font-medium rounded-xl transition-all"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add/Edit Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-slate-900 rounded-2xl border border-white/20 w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b border-white/10">
              <h2 className="text-xl font-semibold text-white">
                {editingConfig ? 'Edit Tunnel' : 'Add New Tunnel'}
              </h2>
              <button onClick={closeModal} className="p-2 hover:bg-white/10 rounded-lg transition-colors">
                <X className="w-5 h-5 text-blue-300" />
              </button>
            </div>
            
            <form onSubmit={handleSubmit} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-blue-200 mb-2">Tunnel Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-blue-300/50 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  placeholder="e.g., Bangladesh Relay"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-blue-200 mb-2">Country</label>
                  <select
                    value={formData.country}
                    onChange={(e) => setFormData({ ...formData, country: e.target.value as 'bangladesh' | 'india' })}
                    className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="bangladesh">Bangladesh</option>
                    <option value="india">India</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-blue-200 mb-2">Status</label>
                  <select
                    value={formData.status}
                    onChange={(e) => setFormData({ ...formData, status: e.target.value as 'connected' | 'disconnected' | 'configuring' })}
                    className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="connected">Connected</option>
                    <option value="disconnected">Disconnected</option>
                    <option value="configuring">Configuring</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-blue-200 mb-2">Interface IP</label>
                <input
                  type="text"
                  value={formData.interfaceIp}
                  onChange={(e) => setFormData({ ...formData, interfaceIp: e.target.value })}
                  className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-blue-300/50 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  placeholder="e.g., 10.100.0.1"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-blue-200 mb-2">Endpoint</label>
                <input
                  type="text"
                  value={formData.endpoint}
                  onChange={(e) => setFormData({ ...formData, endpoint: e.target.value })}
                  className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white placeholder-blue-300/50 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  placeholder="e.g., relay.iptsp.local:51820"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-blue-200 mb-2">Port</label>
                <input
                  type="number"
                  value={formData.port}
                  onChange={(e) => setFormData({ ...formData, port: parseInt(e.target.value) })}
                  className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                  required
                />
              </div>

              <div className="flex gap-3 pt-4">
                <button
                  type="button"
                  onClick={closeModal}
                  className="flex-1 px-6 py-3 bg-white/10 hover:bg-white/20 text-white font-medium rounded-xl transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-xl transition-all shadow-lg shadow-purple-500/30"
                >
                  {editingConfig ? 'Update' : 'Create'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
